#!/usr/bin/env node
/* Pheenyx Capital - Pipeline Workflow
   tools/make-env.js
   ------------------------------------------------------------------
   Builds .env.local from your Firebase service account JSON, so you
   never have to hand-copy the private key (getting its line breaks
   wrong is the single most common reason the webhook endpoint fails).

       node tools/make-env.js

   Reads : tools/service-account.json   (download from Firebase console:
                                         Project settings -> Service accounts
                                         -> Generate new private key)
   Writes: .env.local                   (gitignored - never committed)

   Keeps any INBOUND_SECRET already in .env.local; generates a strong one
   if there isn't one yet. Then prints the block to paste into Vercel.   */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const SA = path.join(__dirname, 'service-account.json');
const ENV = path.join(ROOT, '.env.local');

function die(msg) { console.error('\n  ' + msg + '\n'); process.exit(1); }

/* ---- keep an existing secret rather than invalidating the GHL webhook ---- */
let existing = {};
if (fs.existsSync(ENV)) {
  fs.readFileSync(ENV, 'utf8').split('\n').forEach(line => {
    const m = line.match(/^\s*([A-Z_]+)\s*=\s*(.*)$/);
    if (m) existing[m[1]] = m[2].replace(/^"(.*)"$/, '$1');
  });
}
const secret = existing.INBOUND_SECRET || crypto.randomBytes(24).toString('base64url');

/* ---------------------------- service account ---------------------------- */
if (!fs.existsSync(SA)) {
  console.log('\n  No tools/service-account.json yet.');
  console.log('  Firebase console -> Project settings -> Service accounts');
  console.log('  -> Generate new private key -> save it as tools/service-account.json');
  console.log('\n  Writing .env.local with the parts I can fill in; re-run this');
  console.log('  once the key file is there and it will complete itself.\n');
}

let sa = null;
if (fs.existsSync(SA)) {
  try { sa = JSON.parse(fs.readFileSync(SA, 'utf8')); }
  catch (e) { die('tools/service-account.json is not valid JSON: ' + e.message); }

  /* the usual mix-up: the WEB config pasted in place of the service account */
  if (sa.apiKey || sa.appId || sa.authDomain) {
    die('That is the Firebase WEB config, not the service account.\n\n' +
        '  The web config (apiKey / authDomain / appId) is public and already\n' +
        '  lives in assets/js/config.js - it is not what this file needs.\n\n' +
        '  What is needed is a downloaded key file containing "client_email"\n' +
        '  and "private_key":\n\n' +
        '    Firebase console -> Project settings -> SERVICE ACCOUNTS tab\n' +
        '    -> Generate new private key -> save it as tools/service-account.json');
  }
  ['project_id', 'client_email', 'private_key'].forEach(k => {
    if (!sa[k]) die('tools/service-account.json is missing "' + k + '".\n' +
      '  Re-download it: Firebase console -> Project settings -> Service accounts\n' +
      '  -> Generate new private key.');
  });
  if (!/BEGIN PRIVATE KEY/.test(sa.private_key)) die('The private_key in that file does not look like a key.');
}

const projectId = (sa && sa.project_id) || existing.FIREBASE_PROJECT_ID || 'ghl-phc-pipeline';
const clientEmail = (sa && sa.client_email) || existing.FIREBASE_CLIENT_EMAIL || '';
/* one line, \n escaped - the endpoint converts them back */
const privateKey = sa ? sa.private_key.replace(/\n/g, '\\n') : (existing.FIREBASE_PRIVATE_KEY || '');

const body = [
  '# Generated by tools/make-env.js - DO NOT COMMIT (already gitignored).',
  '# These four are for the GoHighLevel webhook endpoint only.',
  '# In production they go in: Vercel -> Settings -> Environment Variables.',
  '',
  'INBOUND_SECRET=' + secret,
  'FIREBASE_PROJECT_ID=' + projectId,
  'FIREBASE_CLIENT_EMAIL=' + clientEmail,
  'FIREBASE_PRIVATE_KEY="' + privateKey + '"',
  ''
].join('\n');

fs.writeFileSync(ENV, body, 'utf8');

const done = !!(secret && projectId && clientEmail && privateKey);
console.log('\n  Wrote .env.local\n');
console.log('  INBOUND_SECRET        ' + secret);
console.log('  FIREBASE_PROJECT_ID   ' + projectId);
console.log('  FIREBASE_CLIENT_EMAIL ' + (clientEmail || '(still empty - need the service account file)'));
console.log('  FIREBASE_PRIVATE_KEY  ' + (privateKey ? '(' + privateKey.length + ' chars, escaped for one line)' : '(still empty - need the service account file)'));

if (done) {
  console.log('\n  All four set. To load them into Vercel:');
  console.log('    - open  Vercel -> your project -> Settings -> Environment Variables');
  console.log('    - paste the whole contents of .env.local into the bulk "paste .env" box');
  console.log('    - then redeploy:  vercel --prod      (env vars only apply to a NEW deployment)');
  console.log('\n  Keep INBOUND_SECRET handy - it goes in the GHL webhook action too,');
  console.log('  as an x-inbound-key header or ?key=... on the URL.\n');
} else {
  console.log('\n  Not finished: download the service account key and run this again.\n');
}
