#!/usr/bin/env node
/* Pheenyx Capital - Pipeline Workflow
   tools/make-env.js
   ------------------------------------------------------------------
   Builds .env.local from your Firebase service account JSON, so you
   never have to hand-copy the private key (getting its line breaks
   wrong is the single most common reason the webhook endpoint fails).

       node tools/make-env.js

   Reads : tools/service-account.json   (download from Firebase console:
                                         Project settings -> Service accounts
                                         -> Generate new private key)
   Writes: .env.local                   (gitignored - never committed)

   Keeps any INBOUND_SECRET already in .env.local; generates a strong one
   if there isn't one yet. Then prints the block to paste into Vercel.   */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const SA = path.join(__dirname, 'service-account.json');
const ENV = path.join(ROOT, '.env.local');
const WEB_CONFIG = path.join(ROOT, 'assets', 'js', 'config.js');

function die(msg) { console.error('\n  ' + msg + '\n'); process.exit(1); }

/* ---- keep an existing secret rather than invalidating the GHL webhook ---- */
let existing = {};
if (fs.existsSync(ENV)) {
  fs.readFileSync(ENV, 'utf8').split('\n').forEach(line => {
    const m = line.match(/^\s*([A-Z_]+)\s*=\s*(.*)$/);
    if (m) existing[m[1]] = m[2].replace(/^"(.*)"$/, '$1');
  });
}
const secret = existing.INBOUND_SECRET || crypto.randomBytes(24).toString('base64url');

/* ---------------------------- service account ---------------------------- */
if (!fs.existsSync(SA)) {
  console.log('\n  No tools/service-account.json yet.');
  console.log('  Firebase console -> Project settings -> Service accounts');
  console.log('  -> Generate new private key -> save it as tools/service-account.json');
  console.log('\n  Writing .env.local with the parts I can fill in; re-run this');
  console.log('  once the key file is there and it will complete itself.\n');
}

let sa = null;
if (fs.existsSync(SA)) {
  try { sa = JSON.parse(fs.readFileSync(SA, 'utf8')); }
  catch (e) { die('tools/service-account.json is not valid JSON: ' + e.message); }

  /* the usual mix-up: the WEB config pasted in place of the service account */
  if (sa.apiKey || sa.appId || sa.authDomain) {
    die('That is the Firebase WEB config, not the service account.\n\n' +
        '  The web config (apiKey / authDomain / appId) is public and already\n' +
        '  lives in assets/js/config.js - it is not what this file needs.\n\n' +
        '  What is needed is a downloaded key file containing "client_email"\n' +
        '  and "private_key":\n\n' +
        '    Firebase console -> Project settings -> SERVICE ACCOUNTS tab\n' +
        '    -> Generate new private key -> save it as tools/service-account.json');
  }
  ['project_id', 'client_email', 'private_key'].forEach(k => {
    if (!sa[k]) die('tools/service-account.json is missing "' + k + '".\n' +
      '  Re-download it: Firebase console -> Project settings -> Service accounts\n' +
      '  -> Generate new private key.');
  });
  if (!/BEGIN PRIVATE KEY/.test(sa.private_key)) die('The private_key in that file does not look like a key.');
}

const projectId = (sa && sa.project_id) || existing.FIREBASE_PROJECT_ID || 'ghl-phc-pipeline';
const clientEmail = (sa && sa.client_email) || existing.FIREBASE_CLIENT_EMAIL || '';
/* one line, \n escaped - the endpoint converts them back */
const privateKey = sa ? sa.private_key.replace(/\n/g, '\\n') : (existing.FIREBASE_PRIVATE_KEY || '');

/* ---- the public web config, read from assets/js/config.js -----------------
   These are NOT used by the server - the browser gets them from config.js.
   They are written here so Vercel holds one complete record of the project,
   and so they cannot drift from config.js by being copied out by hand.      */
let web = {};
try {
  const sandbox = {};
  new Function('window', fs.readFileSync(WEB_CONFIG, 'utf8'))(sandbox);
  web = (sandbox.PHX_CONFIG && sandbox.PHX_CONFIG.firebase) || {};
} catch (e) {
  console.log('  (could not read assets/js/config.js: ' + e.message + ')');
}

const body = [
  '# Generated by tools/make-env.js - DO NOT COMMIT (already gitignored).',
  '# Paste this whole file into: Vercel -> Settings -> Environment Variables',
  '# then redeploy - env vars only take effect on a NEW deployment.',
  '',
  '# ---------------------------------------------------------------------',
  '# SIMPLE MODE - these three are all the GHL webhook needs to work.',
  '# Writes go through the public API, so firestore.rules still applies:',
  '# the endpoint may create a submission and nothing else.',
  '# None of these three is a secret except INBOUND_SECRET, which you chose.',
  '# ---------------------------------------------------------------------',
  'INBOUND_SECRET=' + secret,
  'FIREBASE_PROJECT_ID=' + projectId,
  'FIREBASE_API_KEY=' + (web.apiKey || ''),
  '',
  '# ---------------------------------------------------------------------',
  '# FULL MODE - optional. Adds raw-payload storage and de-duplication of',
  '# GoHighLevel retries. These two ARE real secrets: they bypass every',
  '# security rule. Leave them blank to stay in simple mode.',
  '# ---------------------------------------------------------------------',
  'FIREBASE_CLIENT_EMAIL=' + clientEmail,
  'FIREBASE_PRIVATE_KEY="' + privateKey + '"',
  '',
  '# ---------------------------------------------------------------------',
  '# The rest of the public web config - reference only, nothing reads it.',
  '# The browser gets these from assets/js/config.js.',
  '# ---------------------------------------------------------------------',
  'FIREBASE_AUTH_DOMAIN=' + (web.authDomain || ''),
  'FIREBASE_STORAGE_BUCKET=' + (web.storageBucket || ''),
  'FIREBASE_MESSAGING_SENDER_ID=' + (web.messagingSenderId || ''),
  'FIREBASE_APP_ID=' + (web.appId || ''),
  'FIREBASE_MEASUREMENT_ID=' + (web.measurementId || ''),
  ''
].join('\n');

fs.writeFileSync(ENV, body, 'utf8');

const simpleReady = !!(secret && projectId && web.apiKey);
const done = !!(simpleReady && clientEmail && privateKey);
console.log('\n  Wrote .env.local\n');
console.log('  INBOUND_SECRET        ' + secret);
console.log('  FIREBASE_PROJECT_ID   ' + projectId);
console.log('  FIREBASE_API_KEY      ' + (web.apiKey || '(missing from assets/js/config.js)'));
console.log('  FIREBASE_CLIENT_EMAIL ' + (clientEmail || '(blank - optional, full mode only)'));
console.log('  FIREBASE_PRIVATE_KEY  ' + (privateKey ? '(' + privateKey.length + ' chars, escaped)' : '(blank - optional, full mode only)'));

function howToLoad() {
  console.log('    - open  Vercel -> your project -> Settings -> Environment Variables');
  console.log('    - paste the whole contents of .env.local into the bulk "paste .env" box');
  console.log('    - then REDEPLOY (env vars only apply to a new deployment)');
  console.log('\n  Keep INBOUND_SECRET handy - it goes in the GHL webhook action too,');
  console.log('  as an x-inbound-key header or ?key=... on the URL.\n');
}
if (done) {
  console.log('\n  FULL MODE ready - raw payloads kept, GHL retries de-duplicated.');
  howToLoad();
} else if (simpleReady) {
  console.log('\n  SIMPLE MODE ready - the GoHighLevel webhook will work with just');
  console.log('  INBOUND_SECRET, FIREBASE_PROJECT_ID and FIREBASE_API_KEY.');
  howToLoad();
  console.log('  Simple mode does not keep the raw GHL payload and does not spot');
  console.log('  retries. For those, drop the service account JSON at');
  console.log('  tools/service-account.json and run this again.\n');
} else {
  console.log('\n  Not usable yet: FIREBASE_API_KEY could not be read from');
  console.log('  assets/js/config.js. Fill in the Firebase web config there first.\n');
}
